[build]
  command = "npm run build"  # ou o comando que você usa para construir seu projeto
  publish = "build"  # ou o diretório onde seus arquivos construídos são armazenados

[dev]
  command = "npm run start"  # comando para iniciar o servidor de desenvolvimento local
